# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [36]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [37]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

chipo = pd.read_csv(url, sep="\t")

### Step 4. How many products cost more than $10.00?

In [47]:
# clean up prices to only hold value, no "$" sign, and convert them to flat
# prices = [float(price[1:len(price)]) for price in chipo.item_price]

# chipo.item_price = prices
# chipo.item_price

# dropping dupes in that has the same name and quantity
chipo_cleaned = chipo.drop_duplicates(['item_name', 'quantity'], keep="first", inplace=False)

# "The Where condition"
single_quant = chipo_cleaned.quantity == 1
more_than_ten = chipo_cleaned.item_price > 10

chipo_cleaned[single_quant & more_than_ten].item_name.nunique()

12

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [61]:
single_quantity = chipo_cleaned[single_quant][['item_name', 'item_price']]
single_quantity.sort_values(by="item_price", ascending=False)

                                  item_name  item_price
606                        Steak Salad Bowl       11.89
1229                    Barbacoa Salad Bowl       11.89
1132                    Carnitas Salad Bowl       11.89
7                             Steak Burrito       11.75
168                   Barbacoa Crispy Tacos       11.75
39                            Barbacoa Bowl       11.75
738                       Veggie Soft Tacos       11.25
186                       Veggie Salad Bowl       11.25
62                              Veggie Bowl       11.25
57                           Veggie Burrito       11.25
250                           Chicken Salad       10.98
5                              Chicken Bowl       10.98
8                          Steak Soft Tacos        9.25
554                   Carnitas Crispy Tacos        9.25
237                     Carnitas Soft Tacos        9.25
56                      Barbacoa Soft Tacos        9.25
92                       Steak Crispy Tacos        9.25
664                             Steak Salad        8.99
54                               Steak Bowl        8.99
3750                         Carnitas Salad        8.99
21                         Barbacoa Burrito        8.99
27                         Carnitas Burrito        8.99
33                            Carnitas Bowl        8.99
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
44                       Chicken Salad Bowl        8.75
1653                    Veggie Crispy Tacos        8.49
16                          Chicken Burrito        8.49
1694                           Veggie Salad        8.49
1414                                  Salad        7.40
510                                 Burrito        7.40
520                            Crispy Tacos        7.40
673                                    Bowl        7.40
298                       6 Pack Soft Drink        6.49
10                      Chips and Guacamole        4.45
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
674       Chips and Mild Fresh Tomato Salsa        3.00
111     Chips and Tomatillo Red Chili Salsa        2.95
233      Chips and Roasted Chili Corn Salsa        2.95
38    Chips and Tomatillo Green Chili Salsa        2.95
3     Chips and Tomatillo-Green Chili Salsa        2.39
300     Chips and Tomatillo-Red Chili Salsa        2.39
191      Chips and Roasted Chili-Corn Salsa        2.39
0              Chips and Fresh Tomato Salsa        2.39
40                                    Chips        2.15
6                             Side of Chips        1.69
263                       Canned Soft Drink        1.25
28                              Canned Soda        1.09
34                            Bottled Water        1.09

### Step 6. Sort by the name of the item

In [54]:
chipo_cleaned.sort_values(by=['item_name'])

,order_id,quantity,item_name,choice_description,item_price
298,129,1,6 Pack Soft Drink,[Sprite],6.49
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",8.99
1903,768,2,Barbacoa Crispy Tacos,"[Fresh Tomato Salsa, [Sour Cream, Cheese, Rice]]",18.50
168,75,1,Barbacoa Crispy Tacos,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",11.75
1229,501,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.89
56,26,1,Barbacoa Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",9.25
2441,970,5,Bottled Water,NaN,7.50
4152,1660,10,Bottled Water,NaN,15.00
818,338,3,Bottled Water,NaN,3.27
540,225,2,Bottled Water,NaN,3.00
1425,577,4,Bottled Water,NaN,6.00
3599,1443,7,Bottled Water,NaN,10.50
34,17,1,Bottled Water,NaN,1.09
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",22.20
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",7.40
510,214,1,Burrito,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",7.40
18,9,2,Canned Soda,[Sprite],2.18
2235,901,4,Canned Soda,[Sprite],4.36
28,14,1,Canned Soda,[Dr. Pepper],1.09
263,114,1,Canned Soft Drink,[Coke],1.25
3973,1592,4,Canned Soft Drink,[Coke],5.00
492,206,2,Canned Soft Drink,[Diet Coke],2.50
689,284,3,Canned Soft Drink,[Diet Coke],3.75
33,17,1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.99
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25
506,212,2,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",23.50
2581,1024,2,Carnitas Burrito,"[Tomatillo Red Chili Salsa, [Rice, Pinto Beans...",18.50
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.99
...,...,...,...,...,...
520,217,1,Crispy Tacos,[Adobo-Marinated and Grilled Steak],7.40
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],6.78
1414,575,1,Salad,"[Brown Rice, Adobo-Marinated and Grilled Chick...",7.40
3887,1559,8,Side of Chips,NaN,13.52
6,3,1,Side of Chips,NaN,1.69
2944,1170,3,Side of Chips,NaN,5.07
3334,1336,3,Steak Bowl,"[Tomatillo Green Chili (Medium), [Rice, Black ...",26.07
910,377,2,Steak Bowl,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",17.98
54,25,1,Steak Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.99
1255,511,3,Steak Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",27.75
148,67,2,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",17.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
92,40,1,Steak Crispy Tacos,"[Fresh Tomato Salsa, Sour Cream]",9.25
2874,1142,2,Steak Crispy Tacos,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",17.98
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.99
606,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Gua...",11.89
281,123,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",23.78
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
4354,1738,2,Steak Soft Tacos,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",18.50
62,28,1,Veggie Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
846,348,2,Veggie Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Sour Cream,...",16.98
57,26,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75
1653,668,1,Veggie Crispy Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
1694,686,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25

### Step 7. What was the quantity of the most expensive item ordered?

In [78]:
chipo_cleaned.sort_values(by=['item_price'], ascending=False).head(1)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [86]:

veg_sld_bwl = chipo.item_name == 'Veggie Salad Bowl'
len(chipo[veg_sld_bwl])

18

### Step 9. How many times people orderd more than one Canned Soda?

In [89]:
canned_soda = chipo.item_name == 'Canned Soda'
extra = chipo.quantity > 1
len(chipo[canned_soda & extra])

20